### ISSUE TITLE
Labels.

### ISSUE THREAD

**Issue by jolupa** [xhsdf/ob_rmenu#1]
Hi.
There's any possibilities to tweak the script and put a label for the menu title?
Normally in some Openbox menus there's a name at the top with a name, there's any possibilities to include that in the script?
Thanks a lot.

**Comment by xhsdf** [comment]
Hey there!
Not exactly sure what you mean. Can you give an example and what the XML syntax would be?

**Comment by jolupa** [comment]
An example I put this image for the Archlabs menu... They have a title "ArchLabs" at the top. [Image](https://archlabslinux.com/wp-content/uploads/2018/02/ArchLabs_2018-02-07-17_1920x1080.png)
According to the Openbox docs the XML syntax is:
`<menu id="root-menu" label="some-label">
    <separator label="ArchLabs"/>
    <the rest of the menu>`
I hope it helps and is only aesthetic, but adding this can be pretty cool!
Thanks.

**Comment by xhsdf** [comment]
So you just need a named separator? Should be easy. I'll have a look at it tomorrow evening when I'm back home.

**Comment by xhsdf** [comment]
Done. Try adding "label:foobar" as first item in your menu

**Comment by jolupa** [comment]
Works perfect! Thank your very much!!
